In [1]:
import pandas as pd
import numpy as np


# Numpy Arrays and Matrixes

In [7]:
# numpy dizileri
arr = np.array([1,2,3,4])
arr2 = np.array([0,5,4,3])


In [10]:
sub = arr2 - arr
sum = arr2 + arr
div = arr2 / arr
mult = arr2 * arr

print(sub, "\n", sum, "\n", div, "\n", mult)

[-1  3  1 -1] 
 [1 7 7 7] 
 [0.         2.5        1.33333333 0.75      ] 
 [ 0 10 12 12]


In [12]:
m1 = np.random.random((3 ,3))
m2 = np.random.random((3, 3))

In [19]:
# matrix multiplication
# dot product

dot_prod = m1.dot(m2)
dot_prod_2 = m2.dot(m1)

In [ ]:
dot_prod

array([[0.53118715, 1.15952716, 0.77788846],
       [0.41474729, 1.68648329, 1.21233085],
       [0.35110908, 1.22111991, 0.90912331]])

In [20]:
dot_prod_2

array([[0.94537505, 1.40207491, 0.41576023],
       [0.9836871 , 1.57382955, 0.48579545],
       [0.73460481, 1.35106197, 0.60758915]])

# Numpy Operations

In [23]:
arr = np.random.randint(1, 100, 20)
new_arr = arr[arr > 25]
new_arr

array([73, 99, 72, 61, 40, 66, 27, 45, 65, 73, 61, 99, 41, 53])

In [28]:
m3 = np.array([[10, 20], [30, 40], [50, 60]])
m3

array([[10, 20],
       [30, 40],
       [50, 60]])

In [29]:
m3.transpose() # or m3.T

array([[10, 30, 50],
       [20, 40, 60]])

In [33]:
rand_arr = np.random.random((6, 1))
rand_arr

array([[0.75594442],
       [0.35472867],
       [0.88407931],
       [0.45044835],
       [0.4581887 ],
       [0.25637878]])

In [32]:
reshaped_arr = rand_arr.reshape(3, 2)
reshaped_arr

array([[0.89472588, 0.99394726],
       [0.64000776, 0.64977065],
       [0.72290922, 0.68550915]])

# Pandas 